name: bsc_order_status
version: '1.0.0'
config-version: 2

profile: bsc_order_status

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  bsc_order_status:
    staging:
      +schema: DEMO_BSC
      +materialized: view
    marts:
      orders:
        +schema: DEMO_BSC
        +materialized: table
